language: objective-c
os: osx
osx_image: xcode8

-before_install:
 - |
    gem install xcpretty -N --no-ri --no-rdoc
 
script:
- |
    set -o pipefail
    xcodebuild clean test -workspace Example/EFCountingLabel.xcworkspace -scheme EFCountingLabel -destination "platform=iOS Simulator,name=iPhone 6 Plus" -enableCodeCoverage YES | xcpretty
after_success:
- |
    bash <(curl -s https://codecov.io/bash)
    sleep 10
    
